package org.citydb.ade.energy.schema;

public enum ADESequence {
    VOLUMETYPE_SEQ,
    FLOORAREA_SEQ,
    HEIGHTABOVEGROUND_SEQ,
    HEATEXCHANGETYPE_SEQ,
    TRANSMITTANCE_SEQ,
    OPTICALPROPERTIES_SEQ,
    REFLECTANCE_SEQ,
    TIMEVALUESPROPERTI_SEQ,
    PERIODOFYEAR_SEQ,
    DAILYSCHEDULE_SEQ
}
